name: Release update

on:
  push:
    branches: ["master", "nightly"]

jobs:
  Release:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - run: echo ${{ secrets.GITHUB_REF_NAME }}
      - uses: andelf/nightly-release@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.GITHUB_BASE_REF }}
          name: ${{ env.GITHUB_BASE_REF }}
          prerelease: false
          files: |
            ./*.zip
