name: Release update

on:
  push:
    branches: ["master", "nightly"]

permissions: write-all

jobs:
  Release:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - uses: IsaacShelton/update-existing-release@v1.3.3
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          replace: true
          files: >
            *.zip
