name: Update release

on:
  push:
    branches: ["master", "nightly"]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - uses: IsaacShelton/update-existing-release@v1.3.3
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          replace: true
          files: >
            bolt-win64-qt5.15.2.zip
